# Generated by Django 4.2.13 on 2024-12-17 15:40

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "projectCode",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("title", models.CharField(max_length=250)),
                ("metaContent", models.TextField()),
                ("content", models.TextField()),
                (
                    "background",
                    models.ImageField(default="default.png", upload_to="projectImage"),
                ),
            ],
        ),
    ]
