# Generated by Django 4.2.13 on 2024-12-17 15:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("projectCard", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="date_created",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
