# Generated by Django 4.2.13 on 2024-12-18 09:59

from django.db import migrations, models
import projectCard.models


class Migration(migrations.Migration):
    dependencies = [
        ("projectCard", "0002_project_date_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="background",
            field=models.ImageField(
                default="default.png", upload_to=projectCard.models.upload_rename
            ),
        ),
    ]
