# Generated by Django 4.2.13 on 2024-12-18 11:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projectCard", "0003_alter_project_background"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="github",
            field=models.CharField(
                default="https://github.com/aaravharithas", max_length=250
            ),
        ),
    ]
