# Generated by Django 4.2.13 on 2024-12-19 05:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projectCard", "0004_project_github"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="metaContent",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="project",
            name="title",
            field=models.CharField(max_length=100),
        ),
    ]
